(function() {var implementors = {};
implementors["porteurbars"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"struct\" href=\"porteurbars/struct.Error.html\" title=\"struct porteurbars::Error\">Error</a>",synthetic:false,types:["porteurbars::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;RenderError&gt; for <a class=\"struct\" href=\"porteurbars/struct.Error.html\" title=\"struct porteurbars::Error\">Error</a>",synthetic:false,types:["porteurbars::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;TemplateError&gt; for <a class=\"struct\" href=\"porteurbars/struct.Error.html\" title=\"struct porteurbars::Error\">Error</a>",synthetic:false,types:["porteurbars::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;TemplateRenderError&gt; for <a class=\"struct\" href=\"porteurbars/struct.Error.html\" title=\"struct porteurbars::Error\">Error</a>",synthetic:false,types:["porteurbars::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/git2/0.6/git2/error/struct.Error.html\" title=\"struct git2::error::Error\">Error</a>&gt; for <a class=\"struct\" href=\"porteurbars/struct.Error.html\" title=\"struct porteurbars::Error\">Error</a>",synthetic:false,types:["porteurbars::errors::Error"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"porteurbars/struct.Error.html\" title=\"struct porteurbars::Error\">Error</a>",synthetic:false,types:["porteurbars::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>&gt; for <a class=\"struct\" href=\"porteurbars/struct.Error.html\" title=\"struct porteurbars::Error\">Error</a>",synthetic:false,types:["porteurbars::errors::Error"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
